### ISSUE TITLE
Unsupported aerospike version

### ISSUE THREAD

**Issue by leshcat** [aerospike/aerospike-backup-service#245]
While running latest release of Aerospike Backup Service v2.0.0 in K8s:
[https://aerospike.com/docs/cloud/kubernetes/operator/backup-and-restore](https://aerospike.com/docs/cloud/kubernetes/operator/backup-and-restore)

There is an error in outputs of the service:

```
time=2024-10-30T07:50:59.773Z level=ERROR source=/app/aerospike-backup-service/pkg/service/aerospike_service.go:43 msg="Error reading configuration" host=172.10.10.10:3000 err="unsupported version: 7.2.0.1"
time=2024-10-30T07:50:59.850Z level=ERROR source=/app/aerospike-backup-service/pkg/service/aerospike_service.go:43 msg="Error reading configuration" host=172.10.10.11:3000 err="unsupported version: 7.2.0.1"
time=2024-10-30T07:50:59.850Z level=WARN source=/app/aerospike-backup-service/pkg/service/backup_routine_handler.go:191 msg="Could not read aerospike configuration" routine=aerospike-routine
```

Please advise.

Regards,
Aliaksei

**Comment by filkeith** [comment]
Hello! Looks like the problem is in one outdated library, but to be sure we want to reproduce this error. Can you share your aerospike config?

**Comment by filkeith** [comment]
@leshcat and aerospike-backup-service config, too

**Comment by leshcat** [comment]
Sure, if you don't mind i 'll share the CRs with redacted parts:

CR **AerospikeBackupService**:

```
apiVersion: asdb.aerospike.com/v1beta1
kind: AerospikeBackupService
metadata:
  name: aerospikebackupservice
  namespace: aerospike
spec:
  config:
    backup-policies:
      default:
        parallel: 2
        remove-files: KeepAll
    service:
      http:
        port: 8080
    storage:
      # Using IRSA
      s3Storage:
        path: s3://my-bucket/aerospikeBackupService
        s3-endpoint-override: ''
        s3-profile: ''
        s3-region: us-east-1
        type: aws-s3
  image: aerospike/aerospike-backup-service:2.0.0
  secrets:
    - secretName: default-admin-password
      volumeMount:
        mountPath: /etc/aerospike/secret/password.txt
        name: default-admin-password
        subPath: password
  service:
    type: ClusterIP
```

CR **AerospikeBackup**:
```
apiVersion: asdb.aerospike.com/v1beta1
kind: AerospikeBackup
metadata:
  name: aerospike
  namespace: aerospike
spec:
  backupService:
    name: aerospikebackupservice
    namespace: aerospike
  config:
    aerospike-cluster:
      aerospike-aerospike:
        credentials:
          user: antifraud
        seed-nodes:
          - host-name: aerospike.aerospike.svc.cluster.local
            port: 3000
    backup-routines:
      aerospike-aerospike-routine:
        backup-policy: default
        interval-cron: "@daily"
        namespaces: []
        source-cluster: aerospike-aerospike
        storage: s3Storage
```

CR **AerospikeCluster**:
```
apiVersion: asdb.aerospike.com/v1
kind: AerospikeCluster
metadata:
  name: aerospike
  namespace: aerospike
  
spec:
  # Details: https://aerospike.com/docs/cloud/kubernetes/operator/dynamic-config
  enableDynamicConfigUpdate: true
  
  size: 3
  image: aerospike/aerospike-server-enterprise:7.2.0.1
  
  podSpec:
    multiPodPerHost: true
 
  rackConfig:
    namespaces:
      - test-namespace

    racks:
      - id: 1
        zone: us-east-1b
        storage:
          filesystemVolumePolicy:
            cascadeDelete: true
            initMethod: deleteFiles
          blockVolumePolicy:
            cascadeDelete: true
          volumes:
            - name: workdir
              aerospike:
                path: /opt/aerospike
              source:
                persistentVolume:
                  storageClass: gp3
                  volumeMode: Filesystem
                  size: 10Gi
 
            - name: aerospike-config-secret
              source:
                secret:
                  secretName: aerospike-config-secret
              aerospike:
                path: /etc/aerospike/secret
 
            - name: test-namespace
              aerospike:
                path: /dev/test-namespace
              source:
                persistentVolume:
                  storageClass: gp3
                  volumeMode: Block
                  size: 5Gi # Don't confuse with GB (Gigabyte, base 10)
  
  aerospikeAccessControl:
    roles:
      - name: extraadmin
        privileges:
          - sys-admin
          - data-admin
          - udf-admin
          - sindex-admin
          - read-write
          - read-write-udf
          - truncate
    users:
      - name: admin
        secretName: default-admin-password
        roles:
          - sys-admin
          - user-admin
      - name: extraadmin
        secretName: default-admin-password
        roles:
          - extraadmin
  
  aerospikeConfig:
    service:
      feature-key-file: /etc/aerospike/secret/features.conf
    security: {}
    network:
      service:
        port: 3000
      fabric:
        port: 3001
      heartbeat:
        port: 3002
  
    namespaces:  
      - name: test-namespace
        replication-factor: 1
        stop-writes-sys-memory-pct: 90
        storage-engine:
          type: device
          devices:
            - /dev/test-namespace
```
